### ISSUE TITLE
tests fail

### ISSUE THREAD

**Issue by szabgab** [PerlDancer/dancer2-session-mongodb#2]
After changing dist.ini to have
[Prereqs]
Dancer2 = 0.10

dzil install fails like this:

t/00-compile.t ......... ok
# Prerequisite Report:
#    Version Module                             
#   -------- -----------------------------------
#       0.10 Dancer2                            
#       0.10 Dancer2::Core::Role::SessionFactory
#       0.10 Dancer2::Core::Types               
#       6.80 ExtUtils::MakeMaker                
#       3.40 File::Spec::Functions              
#     0.2301 File::Temp                         
#       6.02 HTTP::Date                         
#       1.34 IO::Handle                         
#       1.13 IPC::Open3                         
#       2.59 JSON                               
#       6.05 LWP::UserAgent                     
#       1.32 List::Util                         
#    0.702.2 MongoDB                            
#    0.702.2 MongoDB::MongoClient               
#    0.702.2 MongoDB::OID                       
#   1.003000 Moo                                
#       0.98 Test::More                         
#       2.00 Test::TCP                          
#       1.07 strict                             
#       1.18 warnings                           
t/00-report-prereqs.t .. ok
>> Dancer2 v0.10 server 25749 listening on http://0.0.0.0:50496

#   Failed test 'session cookie set'
#   at t/basic.t line 59.
# undef

#   Failed test 'correct cookie expired'
#   at t/basic.t line 92.
#          got: 'Umi_zy3BPh94rdFabxezYfkbNYb9FJQL'
#     expected: undef

#   Failed test 'session dump correct'
#   at t/basic.t line 142.
#     Structures begin differing at:
#          $got->{is_dirty} = '0'
#     $expected->{is_dirty} = Does not exist
# Looks like you failed 3 tests of 30.
t/basic.t .............. 
Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/30 subtests

**Comment by cromedome** [comment]
Is this still an issue for you?

**Comment by szabgab** [comment]
I've just tested and I could install Dancer2-Session-MongoDB-0.004 on Dancer2 version 0.201000 and then it successfully tested on Dancer2 version 0.202000 as well.

**Comment by cromedome** [comment]
Thanks for checking!
