### ISSUE TITLE
Test failure (Other one)

### ISSUE THREAD

**Issue by pierreact** [PerlDancer/dancer2-session-mongodb#4]
# cpan install Dancer2::Session::MongoDB
Going to read '/root/.cpan/Metadata'
  Database was generated on Tue, 28 Oct 2014 15:53:35 GMT
Running install for module 'Dancer2::Session::MongoDB'
Running make for D/DA/DAGOLDEN/Dancer2-Session-MongoDB-0.002.tar.gz
Checksum for /root/.cpan/sources/authors/id/D/DA/DAGOLDEN/Dancer2-Session-MongoDB-0.002.tar.gz ok

  CPAN.pm: Going to build D/DA/DAGOLDEN/Dancer2-Session-MongoDB-0.002.tar.gz

Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Dancer2::Session::MongoDB
Writing MYMETA.yml and MYMETA.json
cp lib/Dancer2/Session/MongoDB.pm blib/lib/Dancer2/Session/MongoDB.pm
Manifying 1 pod document
  DAGOLDEN/Dancer2-Session-MongoDB-0.002.tar.gz
  /usr/bin/make -- OK
Running make test
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-compile.t ......... ok   
t/00-report-prereqs.t .. # Prerequisite Report:
#      Version Module                             
#   ---------- -----------------------------------
#     0.153000 Dancer2                            
#     0.153000 Dancer2::Core::Role::SessionFactory
#     0.153000 Dancer2::Core::Types               
#         7.00 ExtUtils::MakeMaker                
#         1.19 File::Find                         
#         3.47 File::Spec::Functions              
#         0.22 File::Temp                         
#         6.02 HTTP::Date                         
#         2.90 JSON                               
#         6.04 LWP::UserAgent                     
#         1.41 List::Util                         
#   v0.706.0.0 MongoDB                            
#   v0.706.0.0 MongoDB::MongoClient               
#   v0.706.0.0 MongoDB::OID                       
#     1.006001 Moo                                
#     1.001008 Test::More                         
#         2.06 Test::TCP                          
#         1.04 strict                             
#         1.12 warnings                           
t/00-report-prereqs.t .. ok   
t/basic.t .............. Can't locate object method "port" via package "HTTP::Server::PSGI" at t/basic.t line 211.
cannot open port: 50370 at /usr/local/share/perl/5.14.2/Test/TCP.pm line 51.
t/basic.t .............. Dubious, test returned 111 (wstat 28416, 0x6f00)
No subtests run 

Test Summary Report
-------------------
t/basic.t            (Wstat: 28416 Tests: 0 Failed: 0)
  Non-zero exit status: 111
  Parse errors: No plan found in TAP output
Files=3, Tests=2, 17 wallclock secs ( 0.02 usr  0.00 sys +  0.96 cusr  0.10 csys =  1.08 CPU)
Result: FAIL
Failed 1/3 test programs. 0/2 subtests failed.
make: *** [test_dynamic] Error 111
  DAGOLDEN/Dancer2-Session-MongoDB-0.002.tar.gz
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports DAGOLDEN/Dancer2-Session-MongoDB-0.002.tar.gz
Running make install
  make test had returned bad status, won't install without force

**Comment by cromedome** [comment]
Resolved by b6f8dfb1156d6b9c79a2fa29914fda6ff5601004. Closing. Thanks for reporting!
